/* ============================================================
   NEXORIA — vote.js
   Reads VOTE_SITES + VOTE_REWARDS from vote-config.js
   and builds the page. Do NOT edit this file —
   all changes go in vote-config.js.
   ============================================================ */

/* ── Render reward pills strip ────────────────────────────── */
function renderRewards() {
  const el = document.getElementById('rewardsStrip');
  if (!el || !window.VOTE_REWARDS) return;
  el.innerHTML = VOTE_REWARDS.map(r => `
    <div class="reward-pill">
      <span class="rp-icon">${r.icon}</span>
      <div>
        <span class="rp-label">${r.label}</span>
        <span class="rp-desc">${r.desc}</span>
      </div>
    </div>`).join('');
}

/* ── Render vote site cards ───────────────────────────────── */
function renderSites() {
  const grid  = document.getElementById('sitesGrid');
  const count = document.getElementById('sitesCount');
  if (!grid || !window.VOTE_SITES) return;

  const active = VOTE_SITES.filter(s => s.active !== false);
  if (count) count.innerHTML = `<strong>${active.length}</strong> sites available`;

  // Restore voted state from sessionStorage
  let voted = [];
  try { voted = JSON.parse(sessionStorage.getItem('nex_voted') || '[]'); } catch(e) {}

  grid.innerHTML = active.map((site, i) => {
    const isVoted = voted.includes(i);
    return `
    <div class="site-card${isVoted ? ' voted' : ''}" id="sc-${i}">
      <div class="sc-top">
        <span class="sc-icon">${site.icon}</span>
        <div>
          <div class="sc-name">${site.name}</div>
          <div class="sc-cool">⏱ ${site.cooldown}</div>
        </div>
      </div>
      <div class="sc-reward">🏆 ${site.reward}</div>
      <a class="sc-btn${isVoted ? ' sc-btn--voted' : ''}"
         href="${site.url}"
         target="_blank"
         rel="noopener noreferrer"
         onclick="markVoted(${i})">
        ${isVoted ? '✔ Voted' : 'Vote Now →'}
      </a>
    </div>`;
  }).join('');
}

/* ── Mark a site as voted ─────────────────────────────────── */
function markVoted(i) {
  setTimeout(() => {
    const card = document.getElementById('sc-' + i);
    const btn  = card && card.querySelector('.sc-btn');
    if (card) card.classList.add('voted');
    if (btn)  { btn.textContent = '✔ Voted'; btn.classList.add('sc-btn--voted'); }

    try {
      const v = JSON.parse(sessionStorage.getItem('nex_voted') || '[]');
      if (!v.includes(i)) { v.push(i); sessionStorage.setItem('nex_voted', JSON.stringify(v)); }
    } catch(e) {}

    // Check if all voted
    const total = VOTE_SITES.filter(s => s.active !== false).length;
    const done  = JSON.parse(sessionStorage.getItem('nex_voted') || '[]').length;
    if (done >= total && typeof showToast === 'function') {
      showToast('🎉 All sites voted! Use /voterewards in-game to claim.');
    }
  }, 200);
}

/* Expose for console use */
function clearVotedState() {
  sessionStorage.removeItem('nex_voted');
  document.querySelectorAll('.site-card').forEach(c => c.classList.remove('voted'));
  document.querySelectorAll('.sc-btn').forEach(b => { b.textContent = 'Vote Now →'; b.classList.remove('sc-btn--voted'); });
}

/* ── Boot — runs immediately (scripts are at bottom of body) ── */
renderRewards();
renderSites();